name: Deploy simple hello app to GKE

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: vincent-demo-training    # TODO: update to cluster name
  GKE_ZONE: asia-southeast1-b	   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-hello-app # TODO: update deployment name if changed in deployment.yaml

jobs:
  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    # Deploy sample image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f ../../deployment.yml
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide